# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=true
org.gradle.parallel=true

deps.fabric_loader=0.18.4
deps.neoforge=26.1.2.78
deps.fml=11.0.0
deps.yacl=3.9.5+26.1
deps.spruceui=10.0.0+26.1
deps.yumi_mc_foundation=1.0.0-beta.2+26.1

deps.forgified_fabric_loader=2.5.84+0.19.3+26.1.2
deps.forgified_fabric_networking_api=6.3.1+134bcbaa4c
deps.forgified_fabric_api_base=2.0.3+b11575294c

mod.version=2.11.1
mod.name=SkinShuffle
mod.id=skinshuffle